"$schema" = 'https://starship.rs/config-schema.json'

# Catppuccin
palette = "dracula"

# Global format
format = """
[ \uE21C  ](bg:bg fg:bold purple)[\uE0B0](fg:bg)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character
"""

right_format = """$cmd_duration"""

# General config
add_newline = true

[line_break]
disabled = false

[username]
style_user = "fg:bold cyan"
style_root = "fg:bold red"
show_always = false
format = "[ $user]($style)"

[hostname]
ssh_only = true
style = "bg:darkbg fg:bold yellow"
format = "[@$hostname]($style)"

[directory]
truncation_symbol = "../"
truncation_length = 4
style = "bg:bg fg:bold purple"
read_only = "\uF023"
read_only_style = "bg:bg fg:red"
format = "[\uE0B0](fg:darkbg bg:bg)[ $path]($style)[ $read_only ]($read_only_style)[\uE0B0 ](fg:bg)"

[character]
success_symbol = "[\uE285](fg:green)"
error_symbol = "[\uE009](fg:red)"
vicmd_symbol = "[\uE285](fg:pink)"
format = "$symbol "

[git_branch]
style = "bg:bg fg:bold yellow"
format = "[\uE0B0](fg:darkbg bg:bg)[ $symbol$branch(:$remote_branch)]($style)"

[git_status]
style = "bg:bg fg:pink"
format = "[ \u003C](bg:bg fg:pink)[$all_status$ahead_behind]($style)[\u003E ](bg:bg fg:pink)[\uE0B0 ](fg:bg)"

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

# Define Dracula color palette
[palettes.dracula]
darkbg = "#21222C"
bg = "#282a36"
cl = "#44475a"
fg = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
